# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Meteor container image

on:
  #  push:
  #    branches: [ 'release' ]
  workflow_dispatch:

env:
  #CONTAINER_REGISTRY: ghcr.io/${{ github.repository_owner }}/
  CONTAINER_REGISTRY: "@zododev/"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        #run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $CONTAINER_REGISTRY -u ${{ github.actor }} --password-stdin
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Build and push image
        run: cd ./meteor && ./build.sh
